import Head from "next/head";
import Image from "next/image";
import LOGO from "../../assets/swissborg-logo.png";

export default function Home() {
  return (
    <>
      <Head>
        <title>CryptoDawg</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex text-primary">
        <div className="w-[35%] h-screen bg-[#e3edff]">
          <div className="flex items-center m-[30px]">
            <Image
              src={LOGO}
              alt="LOGO"
              className="w-[35px] h-[40px] mr-[10px]"
            />
            <span className="text-[2.2rem] lg:text-[2.5rem] leading-[46px] font-commonsDemiBold mt-[10px]">
              CryptoDawg
            </span>
          </div>
        </div>
        <div className="w-[58.5%] h-screen p-[46px]">
          <p className="font-commonsDemiBold text-6xl pt-[10px]">
            Welcome to CryptoDawg
          </p>
          <p className="font-commonsRegular text-[22px] mt-[14px] mb-[47px]">
            We&apos;re excited to have you on board. Let&apos;s get started by
            creating your account.
          </p>
          <form action="" method="post">
            <div className="flex flex-col gap-4">
              <div className="relative font-commonsRegular">
                <input
                  type="text"
                  className="w-[358px] h-[51px] outline-none border-[#c4c4c4] border-[1px] rounded-md px-4 hover:border-black focus:border-blue-500 focus:border-2"
                />
                <p className="absolute -top-2 left-4 bg-white px-1 text-sm">
                  First Name*
                </p>
              </div>
              <div className="relative font-commonsRegular">
                <input
                  type="text"
                  className="w-[358px] h-[51px] outline-none border-[#c4c4c4] border-[1px] rounded-md px-4 hover:border-black focus:border-blue-500 focus:border-2"
                />
                <p className="absolute -top-2 left-4 bg-white px-1 text-sm">
                  Last Name*
                </p>
              </div>
              <div className="relative font-commonsRegular">
                <input
                  type="email"
                  className="w-[358px] h-[51px] outline-none border-[#c4c4c4] border-[1px] rounded-md px-4 hover:border-black focus:border-blue-500 focus:border-2"
                />
                <p className="absolute -top-2 left-4 bg-white px-1 text-sm">
                  Email*
                </p>
              </div>
              <div className="relative font-commonsRegular">
                <input
                  type="password"
                  className="w-[358px] h-[51px] outline-none border-[#c4c4c4] border-[1px] rounded-md px-4 hover:border-black focus:border-blue-500 focus:border-2"
                />
                <p className="absolute -top-2 left-4 bg-white px-1 text-sm">
                  Password*
                </p>
              </div>
            </div>
          </form>
        </div>
      </main>
    </>
  );
}
